Make tests less flaky
Tests sometimes fail at exactly 10m of waiting for deployments to start
due to

```
Error: Action failure: rollout of deploy/posthog-web
The process '/usr/local/bin/kubectl' failed with exit code 1

error: deployment "posthog-web" exceeded its progress deadline
```

This is caused by a default in kubernetes - each deployment has
`spec.progressDeadlineSeconds` set to 600.

This PR increases that threshold to 1200 during tests.

This deadline seems to only affects `kubectl rollout` commands, so no
production effects here.