release: update chart to default to 1.34.0 (#340)
* bump to 1.34.0

* unstable test

* stable update

* test(statsd-external): disable persistence for clickhouse

We were getting this test failing in CI consistently, see
https://github.com/PostHog/charts-clickhouse/runs/5735048704?check_suite_focus=true

The error suggests there is already a replica for a table, so I'm
thinking the test is somehow reusing a volume from a previous run
:fingerscrossed:

If successful, will update all to use no persistence.

* test: delete pvs in namespace posthog as part of k8s kubetest cleanup

This removes the individual fix from the previous fix and replaces with
something more general, to ensure we don't have any left over pvs.

* fix lint

* pin click to 8.0.4

* test: disable clickhouse persistence in test, avoid reusing volumes

We were getting an issue with a table replica already existing, so am
trying to avoid.

* chore: disable zookeeper persistence

We're having issues with tables seemingly being created, e.g. replica
already exists, I suspect that's because we still have the replica path
in zookeeper :shrug:

* chore: move persistence settings up

* chore: disable kafka persistence in kubetest

I see the kafka pods end up trying to connect to the wrong cluster:

```
kafka.common.InconsistentClusterIdException: The Cluster ID pO81BBLlRrK_vNSIWg4Awg doesn't match stored clusterId Some(vr6AYsp_TYuFlEzJVyQJpQ) in meta.properties. The broker is trying to join the wrong cluster. Configured zookeeper.connect may be wrong.
        at kafka.server.KafkaServer.startup(KafkaServer.scala:218)
        at kafka.Kafka$.main(Kafka.scala:109)
        at kafka.Kafka.main(Kafka.scala)
```

disabling persistence to avoid reusing the old cluster id

Co-authored-by: Li Yi Yu <li@posthog.com>