Fix bumping chart version (#303)
https://github.com/PostHog/charts-clickhouse/pull/294 broke this by not
adding the new repo prior to packaging the helm chart in gh action

Error was:
```
2s
Run helm/chart-releaser-action@v1.2.1
Run owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
Looking up latest tag...
Discovering changed charts since 'posthog-15.2.0'...
Installing chart-releaser...
Adding cr directory to PATH...
Packaging chart 'charts/posthog'...
Error: no repository definition for https://grafana.github.io/helm-charts
Usage:
  cr package [CHART_PATH] [...] [flags]
```