Proposal: Raise errors if using now-unsupported values (#261)
* Proposal: Raise errors if unsupported variables are used that were supported in previous versions

Example errors:

```
⟩ helm template charts/posthog/ -f ci/values/k3s.yaml --set redis.host=foo                      09:46:06
Error: execution error at (posthog/templates/web-deployment.yaml:1:4): redis.port, redis.host and redis.password no longer valid. Read more on how to update your values.yaml: https://posthog.com/docs/self-host/deploy/upgrade-notes#upgrading-from-11xx

Use --debug flag to render out invalid YAML
```

```
⟩ helm upgrade --install -f ci/values/k3s.yaml posthog charts/posthog --debug --timeout 30m --set redis.host=foo                                                                                           09:50:50
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml
history.go:56: [debug] getting history for release posthog
upgrade.go:123: [debug] preparing upgrade for posthog
Error: UPGRADE FAILED: execution error at (posthog/templates/web-deployment.yaml:1:4): redis.port, redis.host and redis.password no longer valid. Read more on how to update your values.yaml: https://posthog.com/docs/self-host/deploy/upgrade-notes#upgrading-from-11xx
helm.go:81: [debug] execution error at (posthog/templates/web-deployment.yaml:1:4): redis.port, redis.host and redis.password no longer valid. Read more on how to update your values.yaml: https://posthog.com/docs/self-host/deploy/upgrade-notes#upgrading-from-11xx
UPGRADE FAILED
main.newUpgradeCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:157
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```

* Better error formatting

* Add messages on clickhouseOperator

* Fix typo

* certManager error

* Move code around to make more sense

* Remove dead values from tests